routes:
  /: home
collections:
  /play/:
    permalink: /play/{slug}/
    template: play
    filter: primary_tag:play
    data: tag.play
  /travel/:
    permalink: /travel/{slug}/
    template: travel
    filter: primary_tag:travel
    data: tag.travel
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
